name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # waiting on: https://github.com/actions/setup-node/issues/531
      - run: corepack enable
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install deps and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          rm -rf node_modules

      - name: test built package on node@24
        working-directory: ./package-test/
        run: |
          pnpm install --frozen-lockfile

          node -v
          node test.cjs
          node test.mjs

        # Not using a matrix here since it's simpler
        # to just duplicate it and not spawn new instances

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
      - name: test build package on node@22
        working-directory: ./package-test/
        run: |
          node -v
          node test.cjs
          node test.mjs
